### ISSUE TITLE
Use bit fields instead of chars for parsed cron_expr

### ISSUE THREAD

**Issue by Niondir** [staticlibs/ccronexpr#2]
Hey,
I like the lib but it's a bit useless for Embedded systems due to the amount of memory it is using. A parsed CRON expression has ~8 times more bit's than it needs. You could just store the "flags" in bits instead of chars to dramatically reduce memory consumption.

I'm also looking for alternatives. If I do not find anything better I might also start to refactor it.

**Comment by staticlibs** [comment]
Hi, this lib originates from java one, so yes, not ideal for restrictive environments. I haven't found anything suitable (besides in java and golang) before writing this. Will happily accept patches for lower memory consumption.

**Comment by Niondir** [comment]
As of now I'm using the lib as it is on a Cortex M3 but only need 3 cron expressions. I will spend more time on patching the lib when I get time or have the need. 

So far it works like a charm :)

**Comment by Sanaloht** [comment]
I created a pull request in #4 to solve this issue. Please have a look.

**Comment by staticlibs** [comment]
Merged #4 , closing the issue.
