### ISSUE TITLE
next day error

### ISSUE THREAD

**Issue by xunmenging** [staticlibs/ccronexpr#26]
the next day of  expression  "0 15 10 ? * 6#3" is error

**Comment by staticlibs** [comment]
Thanks for the report! Unfortunately I don't have free cycles to dig it. If this is actually a bug - I can happily accept a PR for it.

**Comment by xunmenging** [comment]
Lib does not allow for cron expression with Year and L、W、# as specified in Quartz

**Comment by niondir** [comment]
Support for "W" is something we actually really need.

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
