### ISSUE TITLE
Arduino support

### ISSUE THREAD

**Issue by FedeBev** [staticlibs/ccronexpr#31]
Hi there

thanks for this work!
It would be great to add support for SAMD21 arduino family, like mkr nb 1500, mkr GSM 1400, mkr wifi 1010 and so on..

In my opinion the following change would be enough:
https://github.com/staticlibs/ccronexpr/blob/17475e10c2053650a86b1d25a692c2c20d74c420/ccronexpr.c#L106

becomes

```c
#elif defined(ESP8266) || defined(ESP_PLATFORM) || defined(TARGET_LIKE_MBED) || defined(__SAMD21G18A__)
```

I'm not sure if a change if also required here
https://github.com/staticlibs/ccronexpr/blob/17475e10c2053650a86b1d25a692c2c20d74c420/ccronexpr.c#L88
but leaving that line as-is in my case seems to work.

If this if fine for you I'll be happy to submit a PR.

Thanks again!

**Comment by staticlibs** [comment]
Hi, sure, more platforms are always welcome, I will happily accept a PR that passes CI checks.

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
