### ISSUE TITLE
cron_prev 29-feb infinite loop

### ISSUE THREAD

**Issue by JJM1987** [staticlibs/ccronexpr#32]
cron_prev function infinite loop on 29 February. Issue occurs in non leap years. 

**Example infinite loop:**
Expression: "* * * 29 2 *"
Current time: 2021-12-7 12:00:00 

**Example correct result:**
Expression: "* * * 29 2 *"
Current time: 2020-12-7 12:00:00

**Comment by staticlibs** [comment]
Thanks for the report! This is a nasty bug, will try to fix it.

**Comment by alenloncaric** [comment]
Hi,

was this bug ever fixed?

Thank you!

BR

**Comment by ghseb** [comment]
@alenloncaric Just tried adding `check_next("* * * 29 2 *",  	"2021-12-07_12:00:00", "2024-02-29_00:00:00");` to the tests and it seems to work as expected (at lease on my toolchain with minor local changes).

Probably it makes sense to check it yourself.

**Comment by exander77** [comment]
@ghseb He complains about cron_prev and not cron_next.

**Comment by exander77** [comment]
This is the same bug as: https://github.com/staticlibs/ccronexpr/issues/35

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
