### ISSUE TITLE
compile with __LP64__ got an error

### ISSUE THREAD

**Issue by BIGGIE27** [staticlibs/ccronexpr#33]
[2021-06-07 15:18:00.994] In file included from jni/../../../ccronexpr.h:37:
909[2021-06-07 15:18:00.994] D:/android-ndk/android-ndk-r20b/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\time64.h:36:2: error: Your time_t is already 64-bit.
910[2021-06-07 15:18:00.994] #error Your time_t is already 64-bit.
911[2021-06-07 15:18:00.994]  ^
912[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:133:5: error: unknown type name 'time64_t'
913[2021-06-07 15:18:00.994]     time64_t result = timegm64(tm);
914[2021-06-07 15:18:00.994]     ^
915[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:133:23: error: use of undeclared identifier 'timegm64'
916[2021-06-07 15:18:00.994]     time64_t result = timegm64(tm);
917[2021-06-07 15:18:00.994]                       ^
918[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:153:12: error: use of undeclared identifier 'gmtime_r'
919[2021-06-07 15:18:00.994]     return gmtime_r(date, out);
920[2021-06-07 15:18:00.994]            ^
921[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:158:7: error: member access into incomplete type 'struct tm'
922[2021-06-07 15:18:00.994]     tm->tm_isdst = -1;
923[2021-06-07 15:18:00.994]       ^
924[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:102:30: note: forward declaration of 'bd_baselib::tm'
925[2021-06-07 15:18:00.994] time_t cron_mktime_gm(struct tm *tm) {
926[2021-06-07 15:18:00.994]                              ^
927[2021-06-07 15:18:00.994] jni/../../../ccronexpr.cpp:159:12: error: use of undeclared identifier 'mktime'; did you mean 'mktemp'?
928[2021-06-07 15:18:00.994]     return mktime(tm);
929[2021-06-07 15:18:00.994]            ^~~~~~
930[2021-06-07 15:18:00.994]            mktemp

**Comment by exander77** [comment]
This doesn't look like output from a compilation with `__LP64__`. On the contrary, it looks like you are trying to compile without `__LP64__` on 64-bit platform.

And the error informs you, that you are trying to convert already 64-bit `time64_t` variable.

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
