### ISSUE TITLE
Add support for L and W as specified in Quartz

### ISSUE THREAD

**Issue by niondir** [staticlibs/ccronexpr#34]
Like specified here: http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

We will need an implementation that supports "L" and "W" characters.

We might schedule it for internal development and provide a pull request. If anyone has started on this topic, feedback is welcome.

**Comment by exander77** [comment]
I have made my own fork (to build super tiny cron daemon) that covers these features. Feedback appreciated: https://github.com/exander77/supertinycron

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
