### ISSUE TITLE
cron_parse_expr valid check 

### ISSUE THREAD

**Issue by rexdf** [staticlibs/ccronexpr#5]
cron_parse_expr parse the following two strings with no err.

```
"* * * 30 2 *"
"* * * 31 4 *"
```

**Comment by staticlibs** [comment]
Thanks for the report, that is a real bug. But I cannot see the obvious easy way to fix it right now. Will happily accept a patch for it. Or will revisit it later.

**Comment by exander77** [comment]
I don't think this is a bug. It is perfectly valid to check for these dates.

Cron has no idea about underlying calendar. If and when We decide to have another 30th February is completely up to us and cron should work without a change under such conditions.

There were at least two instances of 30th February in history:
February 30, 1712 (Sweden)
February 30, 1930 (Soviet Union)

Cron doesn't decide calendar, it follows it.

**Comment by staticlibs** [comment]
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.
